### PR TITLE
Visualise inertials (from all IMUs)

### PR DESCRIPTION
**Pull request by nunoguedelha**
Implements #124 .

### CODE REVIEW

**Comment by nunoguedelha** [comment]
Hi @traversaro , I have a doubt about the torso data format (/icub/torso/inertialGYRO), I have to check with @S-Dafarra , but the changes are already reviewable.

**Review by traversaro — APPROVED** [review]
Ok for me, moduling the parsing that probably is blocked by understanding the semantics of the data.

**Comment by nunoguedelha** [comment]
> Ok for me, moduling the parsing that probably is blocked by understanding the semantics of the data.

After discussing with @S-Dafarra , we decided to drop the torso "inertialGYRO" configuration since there is no actual IMU on the torso.

Pushing a commit shortly. I'll merge the PR directly without a new approval if that's ok for you.

**Comment by nunoguedelha** [comment]
> Pushing a commit shortly. I'll merge the PR directly without a new approval if that's ok for you.

Actually, it's simpler to just push the change in the latest ongoing PR #136 .

**Pull request merged**
