### PR TITLE
Run iCub telemetry server and openMCT visualizer in one line command: Iteration 1/2

### PR DESCRIPTION
**Pull request by nunoguedelha**
Implements #25 .

### CODE REVIEW

**Comment by traversaro** [comment]
Could it make sense to document its use somewhere? Furthermore, if we want to stop the program launched with this script, what would be the best way?

**Comment by nunoguedelha** [comment]
I was planning to add all the missing updates and the how to of this script in #22 , but indeed it's better to do it right away here.
With the current implementation, after the servers are launched by this script, we can stop them with a single command `pkill -3 node`. This is acceptable if these servers are the only running Node.js applications.

Another way would be to run from the terminal only the **iCubTelemetryServer**, and then have the server itself run the **openmctStaticServer** as child process using the `spawn` command.
**Actually this should be a better solution** since installing and running the **openmctStaticServer** server separately was only due to the difference in the Node.js versions.

**Comment by nunoguedelha** [comment]
I'll push the changes here.

**Comment by nunoguedelha** [comment]
Further analysis ongoing ... (https://github.com/ami-iit/yarp-openmct/issues/25#issuecomment-914900844)

**Comment by nunoguedelha** [comment]
A class `OpenMctServerHandler` object has been created for handling the child process meant to run the openMCT visualizer. For now:
- The object is instanciated (only a few properties initialized).
- The `nvm use v14.17.0` command is run (unsuccessful, with no effect on other ongoing processes, to be fixed).

@traversaro , although it is not the best way to proceed in general, I would like to freeze the work of this PR as is, merge it, and implement the 2nd iteration (2/2: ) in a new PR on top of al the others. This would simplify the merge of the remaining PRs #20  and #30 . Do you agree?

**Comment by traversaro** [comment]
> @traversaro , although it is not the best way to proceed in general, I would like to freeze the work of this PR as is, merge it, and implement the 2nd iteration (2/2: ) in a new PR on top of al the others. This would simplify the merge of the remaining PRs #20 and #30 . Do you agree?

Ok!

**Review by traversaro — APPROVED** [review]

**Comment by nunoguedelha** [comment]
Second iteration implemented in #32 .

**Pull request merged**
