### PR TITLE
Improve UI for adding vector collection port

### PR DESCRIPTION
**Pull request by nunoguedelha**
Implements #115 .

### CODE REVIEW

**Review by nunoguedelha — COMMENTED** [review]
Update documentation

**Comment by nunoguedelha** [comment]
I forgot the description table for the `conf/dictionaryVectorCollectionsTelemetry.json` dictionary parameters. Adding shortly.

**Comment by nunoguedelha** [comment]
> I forgot the description table for the `conf/dictionaryVectorCollectionsTelemetry.json` dictionary parameters. Adding shortly.

Done @traversaro .

**Comment by nunoguedelha** [comment]
Ciao @traversaro , do you need any additional information regarding this PR? Maybe we could discuss today on Teams?

**Review by traversaro — APPROVED** [review]

**Comment by nunoguedelha** [comment]
Thanks @traversaro .

**Pull request merged**
